M365: Fix log levels in docker compose
If used as is, the docker compose error out with the following error:

error: invalid value 'WARNING' for '--log-level <LOG_LEVEL>': error parsing level: expected one of "error", "warn", "info", "debug", "trace", or a number 1-5

Replace WARNING by warn so that we provide a valid log level.